services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - mongo1
    env_file:
      - .env
    command: npx nodemon src/app.js

  mongo1:
    image: mongo:7
    container_name: mongo1
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db
    command: ["--replSet", "rs0"]

  mongo2:
    image: mongo:7
    container_name: mongo2
    ports:
      - "27018:27017"
    volumes:
      - mongo2_data:/data/db
    command: ["--replSet", "rs0"]

  mongo3:
    image: mongo:7
    container_name: mongo3
    ports:
      - "27019:27017"
    volumes:
      - mongo3_data:/data/db
    command: ["--replSet", "rs0"]

volumes:
  node_modules:
  mongo1_data:
  mongo2_data:
  mongo3_data:
